---
hosts: {{sat_host}}
become: True
gather_facts: False

vars:

  app_version: '8'

  app: 'tomcat'

tasks:

  - name: Unlock Satellite maintain packages
    command: >
       satellite-maintain packages unlock

  - name: Install pulp manifest package
    ansible.builtin.dnf:
      name: python39-pulp_manifest
      state: present

  - name: Lock Satellite maintain packages
    command: >
       satellite-maintain packages lock

  - name: Create directory to host file repsository
    ansible.builtin.file:
      state: directory
      path: '/var/lib/pulp/local_repos/{{app}}/8'
    when: app_version == 8

  - name: Create directory to host file repsository
    ansible.builtin.file:
      state: directory
      path: '/var/lib/pulp/local_repos/{{app}}/9'
    when: app_version == 9
  
  - name: Find latest version of {{app}} 8
    ansible.builtin.command: |
        curl .. https://archive.apache.org/dist/tomcat/tomcat-8/|
        sed -n 's/.*href="\([^"]*\).*/\1/p'| grep '^v'
    register: tomcat_list
    when: app_version == 8
  
  - name: Find latest version of {{app}} 9
    ansible.builtin.command: |
        curl .. https://archive.apache.org/dist/tomcat/tomcat-8/|
        sed -n 's/.*href="\([^"]*\).*/\1/p'| grep '^v'
    register: tomcat_list
    when: app_version == 9

  - name: Download latest version of tomcat
    ansibe.builtin.get_url:
        url: https://archive.apache.org/dist/tomcat/tomcat-8/{{tomcat_list|last}}
        destimation: '/var/lib/pulp/local_repos/{{app}}/8'
    when: app_version == 8

  - name: Download latest version of tomcat
    ansibe.builtin.get_url:
        url: https://archive.apache.org/dist/tomcat/tomcat-9/{{tomcat_list|last}}
        destimation: '/var/lib/pulp/local_repos/{{app}}/9'
    when: app_version == 9

  - name: Add the parent folder into allowed import paths
    ansible.builtin.command: |
        {foreman-installer} --foreman-proxy-content-pulpcore-additional-import-paths /var/lib/pulp/local_repos

  - name: Run the pulp manifest command to create manifest
    ansible.builtin.command: |
        pulp-manifest /var/lib/pulp/local_repos/{{app}}/8
    when: app_version == 8

  - name: Run the pulp manifest command to create manifest
    ansible.builtin.command: |
        pulp-manifest /var/lib/pulp/local_repos/{{app}}/9
    when: app_version == 9
      



    
