---
- name: Create Tomcat file repository
  hosts: "{{sat_host}}"
  become: True
  gather_facts: False

  tasks:

    - name: Unlock Satellite maintain packages
      command: >
        satellite-maintain packages unlock

    - name: Install pulp manifest package
      ansible.builtin.dnf:
        name: python39-pulp_manifest
        state: present

    - name: Lock Satellite maintain packages
      command: >
        satellite-maintain packages lock

    - name: Create directory to host file repsository
      ansible.builtin.file:
        state: directory
        path: '/var/lib/pulp/local_repos/tomcat/8'

    - name: Create directory to host file repsository
      ansible.builtin.file:
        state: directory
        path: '/var/lib/pulp/local_repos/tomcat/9'
  
    - name: Find latest version of tomcat 8
      ansible.builtin.shell: |
          curl .. https://archive.apache.org/dist/tomcat/tomcat-8/|sed -n 's/.*href="\([^"]*\).*/\1/p'| grep '^v'
      register: tomcat_list_8
  
    - name: Find latest version of tomcat 9
      ansible.builtin.shell: |
         curl .. https://archive.apache.org/dist/tomcat/tomcat-9/|sed -n 's/.*href="\([^"]*\).*/\1/p'| grep '^v'    
      register: tomcat_list_9

    - name: Set facts for latest Tomcat 8 version
      ansible.builtin.set_fact:
        tomcat_8_latest_version: "{{ tomcat_list_8.stdout_lines | last | regex_replace('^v', '' ) | regex_replace('/', '') }}"
    
    - name: Set facts for latest Tomcat 9 version
      ansible.builtin.set_fact:
        tomcat_9_latest_version: "{{ tomcat_list_9.stdout_lines | last | regex_replace('^v', '' ) | regex_replace('/', '') }}"

    - ansible.builtin.debug:
        var: tomcat_8_latest_version
    
    - ansible.builtin.debug:
        var: tomcat_9_latest_version

    - name: Download latest version of tomcat 8 tar file
      ansible.builtin.get_url:
        url: https://archive.apache.org/dist/tomcat/tomcat-8/v{{tomcat_8_latest_version}}/bin/apache-tomcat-{{tomcat_8_latest_version}}.tar.gz
        dest: /var/lib/pulp/local_repos/tomcat/8

    - name: Download latest version of tomcat 9 tar file
      ansible.builtin.get_url:
        url: https://archive.apache.org/dist/tomcat/tomcat-9/v{{tomcat_9_latest_version}}/bin/apache-tomcat-{{tomcat_9_latest_version}}.tar.gz
        dest: /var/lib/pulp/local_repos/tomcat/9

    - name: Download latest version of tomcat 8  hash file
      ansible.builtin.get_url:
        url: https://archive.apache.org/dist/tomcat/tomcat-8/v{{tomcat_8_latest_version}}/bin/apache-tomcat-{{tomcat_8_latest_version}}.tar.gz.sha1
        dest: /var/lib/pulp/local_repos/tomcat/8

    - name: Download latest version of tomcat 9 hash file
      ansible.builtin.get_url:
        url: https://archive.apache.org/dist/tomcat/tomcat-9/v{{tomcat_9_latest_version}}/bin/apache-tomcat-{{tomcat_9_latest_version}}.tar.gz.sha1
        dest: /var/lib/pulp/local_repos/tomcat/9

    - name: Add the parent folder into allowed import paths
      ansible.builtin.shell: |
        {foreman-installer} --foreman-proxy-content-pulpcore-additional-import-paths /var/lib/pulp/local_repos

    - name: Run the pulp manifest command to create Tomcat 8 manifest
      ansible.builtin.shell: |
        pulp-manifest /var/lib/pulp/local_repos/tomcat/8
  
    - name: Run the pulp manifest command to create Tomcat 9 manifest
      ansible.builtin.shell: |
        pulp-manifest /var/lib/pulp/local_repos/tomcat/9