---
- name: Find latest versions of tomcat
  ansible.builtin.shell: |
    curl .. {{ item.value.link }}/ | sed -n 's/.*href="\([^"]*\).*/\1/p'| grep '^v'
  register: tomcat_latest_list

# - debug:
#     var: tomcat_latest_list

- name: Set facts for latest Tomcat 8 version
  ansible.builtin.set_fact:
    tomcat_8_latest_version: "{{ tomcat_list_8.stdout_lines | last | regex_replace('^v', '' ) | regex_replace('/', '') }}"

- name: Set facts for latest Tomcat 9 version
  ansible.builtin.set_fact:
    tomcat_9_latest_version: "{{ tomcat_list_9.stdout_lines | last | regex_replace('^v', '' ) | regex_replace('/', '') }}"

# - ansible.builtin.debug:
#     var: tomcat_8_latest_version

# - ansible.builtin.debug:
#     var: tomcat_9_latest_version

- name: Download latest version of tomcat 8 tar file
  ansible.builtin.get_url:
    url: https://archive.apache.org/dist/tomcat/tomcat-8/v{{tomcat_8_latest_version}}/bin/apache-tomcat-{{tomcat_8_latest_version}}.tar.gz
    dest: /var/lib/pulp/local_repos/tomcat/8

- name: Download latest version of tomcat 9 tar file
  ansible.builtin.get_url:
    url: https://archive.apache.org/dist/tomcat/tomcat-9/v{{tomcat_9_latest_version}}/bin/apache-tomcat-{{tomcat_9_latest_version}}.tar.gz
    dest: /var/lib/pulp/local_repos/tomcat/9

- name: Download latest version of tomcat 8  hash file
  ansible.builtin.get_url:
    url: https://archive.apache.org/dist/tomcat/tomcat-8/v{{tomcat_8_latest_version}}/bin/apache-tomcat-{{tomcat_8_latest_version}}.tar.gz.sha1
    dest: /var/lib/pulp/local_repos/tomcat/8

- name: Download latest version of tomcat 9 hash file
  ansible.builtin.get_url:
    url: https://archive.apache.org/dist/tomcat/tomcat-9/v{{tomcat_9_latest_version}}/bin/apache-tomcat-{{tomcat_9_latest_version}}.tar.gz.sha1
    dest: /var/lib/pulp/local_repos/tomcat/9