---
- name: Create Tomcat file repository
  hosts: "{{sat_host}}"
  become: True
  gather_facts: False

  vars_files:
   - vars/app_vars.yml

  tasks:

    - name: Unlock Satellite maintain packages
      command: >
        satellite-maintain packages unlock

    - name: Install pulp manifest package
      ansible.builtin.dnf:
        name: python39-pulp_manifest
        state: present

    - name: Lock Satellite maintain packages
      command: >
        satellite-maintain packages lock

    - name: Check if local pulp directory exist for Tomcat 
      ansible.builtin.stat:
        path: "{{ item.value.app_path }}"
      loop: "{{ lookup('ansible.builtin.dict', tomcat_vars) }}" 
      register: stat_tomcat_pulp_dir

    # - ansible.builtin.debug:
    #     var: tomcat_pulp_dir

    # - ansible.builtin.fail:
    #     msg: I failed it
    
    - name: Create directory to host Tomcat files
      ansible.builtin.file:
        state: "{{ 'directory' if item.stat.exists else 'touch' }}"
        path: "{{ item.stat.path }}"
        group: pulp
        owner: pulp
      loop: "{{ lookup('ansible.builtin.dict', tomcat_vars) }}" 
      when: not stat_tomcat_pulp_dir.stat.exist
      