---
- name: Create Tomcat file repository
  hosts: "{{sat_host}}"
  become: True
  gather_facts: False

  vars_files:
   - vars/app_vars.yml

  tasks:

    - name: Unlock Satellite maintain packages
      command: >
        satellite-maintain packages unlock

    - name: Install pulp manifest package
      ansible.builtin.dnf:
        name: python39-pulp_manifest
        state: present

    - name: Lock Satellite maintain packages
      command: >
        satellite-maintain packages lock

    - name: Check if local pulp directory exist for Tomcat 
      ansible.builtin.stat:
        path: "{{ stat_result.value.app_path }}"
      loop: "{{ tomcat_vars | dict2items }}" 
      loop_control: 
        loop_var: stat_result
      register: stat_pulp_dir

    - ansible.builtin.debug:
        var: stat_pulp_dir.results.files

#    - ansible.builtin.fail:
    #     msg: I failed it

    - name: Collect all files that currently exist under local pulp directory
      ansible.builtin.find:
        paths: "{{ file_collection.stat_result.value.app_path }}"
        hidden: true
        recurse: true
        file_type: any
      register: collected_files
      loop: "{{ stat_pulp_dir.results }}"
      loop_control:
        loop_var: file_collection

    - ansible.builtin.debug:
        var: collected_files.results

    # - ansible.builtin.fail:
    #     msg: I failed it

    - name: Remove all files that currently exist under local pulp directory
      ansible.builtin.file:
        state: absent
        path: "{{ item.stat_result.value.app_path }}"
      loop: "{{ stat_pulp_dir.results }}"
     
    # - ansible.builtin.fail:
    #     msg: I failed it

    - name: Create directory to host Tomcat files
      ansible.builtin.file:
        state: "{{ 'directory' if item.stat.exists else 'directory' }}"
        path: "{{ item.stat_result.value.app_path }}"
        group: pulp
        owner: pulp
      loop: "{{ stat_pulp_dir.results }}" 

    # - ansible.builtin.fail:
    #      msg: I failed it

    - name: Add the parent folder into allowed import paths
      ansible.builtin.command: |
          sudo foreman-installer --foreman-proxy-content-pulpcore-additional-import-paths /var/lib/pulp/local_repos
  
    # - name: Find latest versions of tomcat
    #   ansible.builtin.shell: |
    #       curl .. "{{ item.value.link | quote }}" | sed -n 's/.*href="\([^"]*\).*/\1/p'| grep '^v'
    #   loop: "{{ tomcat_vars | dict2items }}" 
    #   register: tomcat_latest_list

    - name: Find latest versions of tomcat
      ansible.builtin.uri:
        method: GET
        url: "{{ item.value.link }}/"
        return_content: yes
        body_format: json
      loop: "{{ tomcat_vars | dict2items }}" 
      register: tomcat_files

    - ansible.builtin.debug:
        var: tomcat_files