---
- name: Create Tomcat file repository
  hosts: "{{sat_host}}"
  become: True
  gather_facts: False

  vars_files:
   - vars/app_vars.yml

  tasks:

    - name: Unlock Satellite maintain packages
      command: >
        satellite-maintain packages unlock

    - name: Install pulp manifest package
      ansible.builtin.dnf:
        name: python39-pulp_manifest
        state: present

    - name: Lock Satellite maintain packages
      command: >
        satellite-maintain packages lock

    - name: Check if local pulp directory exist for Tomcat 
      ansible.builtin.stat:
        path: "{{ item.app_path }}"
      loop: "{{ tomcat_vars | dict2items }}" 
      register: stat_tomcat_pulp_dir

    - ansible.builtin.debug:
        var: tomcat_pulp_dir

    - ansible.builtin.fail:
        msg: I failed it
    
    - name: Create directory to host Tomcat files
      ansible.builtin.file:
        state: "{{ 'directory' if item.stat.exists else 'directory' }}"
        path: "{{ item.path }}"
        group: pulp
        owner: pulp
      loop: "{{ stat_tomcat_pulp_dir.results }}" 
      