---
- name: Find latest versions of tomcat
  ansible.builtin.shell: |
    curl .. {{ item.value.link }}/ | sed -n 's/.*href="\([^"]*\).*/\1/p'| grep '^v'
  register: tomcat_latest_list

# - debug:
#     var: tomcat_latest_list

- name: Set facts for latest Tomcat version
  ansible.builtin.set_fact:
    tomcat_latest_version: "{{ tomcat_latest_list.stdout_lines | last | regex_replace('^v', '' ) | regex_replace('/', '') }}"

- name: Download latest version of tomcat tar file
  ansible.builtin.get_url:
    url: "{{item.value.link}}/v{{tomcat_latest_version}}/bin/apache-tomcat-{{tomcat_latest_version}}.tar.gz"
    dest: "{{ item.value.app_path }}"